<?xml version="1.0"?>
<package format="3">
  <name>evaluation</name>
  <version>0.1.0</version>
  <description>rosbag 分析与报告生成</description>
  <maintainer email="dev@lcw.local">SwarmCore</maintainer>
  <license>Apache-2.0</license>
  <buildtool_depend>ament_cmake</buildtool_depend>
  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
