<?xml version="1.0"?>
<package format="3">
  <name>perception_camera</name>
  <version>0.1.0</version>
  <description>相机驱动与曝光控制</description>
  <maintainer email="dev@lcw.local">SwarmCore</maintainer>
  <license>BSD-3-Clause</license>
  <buildtool_depend>ament_cmake</buildtool_depend>
  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
